spring:
  application:
    name: dubbo-provider
  redis:
    host: 47.105.165.182
    password:
    port: 6379
    database: 0

server:
  port: 8081

dubbo:
  application:
    name: dubbo-provider
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://127.0.0.1:2181
  provider:
    timeout: 5000



zookeeper:
  server: 127.0.0.1:2181
  lockPath: /springboot/


